name: "Build Package Workflow"
env:
  DOCKER_COMPOSE_VERSION: 1.23.0

on:
  push:
    branches:
      - main
      - release-*
  schedule:
    - cron: 0 2 * * *
jobs:
  BUILD_PACKAGE:
    env:
      BUILD_PACKAGE: true
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #       - uses: google-github-actions/setup-gcloud@main
      #         with:
      #           version: '285.0.0'
      #           project_id: ${{ secrets.GCP_PROJECT_ID }}
      #           service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      #           service_account_key: ${{ secrets.GCP_SA_KEY }}
      #           export_default_credentials: true
      #       - run: gcloud info
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.12
        id: go
      - name: setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 20.10
          docker_channel: stable
      - name: setup Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: src/github.com/goharbor/harbor-arm
      - name: Build Harbor-ARM Images
        run: |
          make download
          make compile_redis
          make prepare_arm_data
          make pre_update
          make compile COMPILETAG=compile_golangimage
          make build GOBUILDTAGS="include_oss include_gcs" BUILDBIN=true NOTARYFLAG=true TRIVYFLAG=true CHARTFLAG=true GEN_TLS=true PULL_BASE_FROM_DOCKERHUB=false
          docker images
          docker save \
            goharbor/harbor-exporter:2.7.0-arm \
            goharbor/chartmuseum-photon:2.7.0-arm \
            goharbor/redis-photon:2.7.0-arm \
            goharbor/trivy-adapter-photon:2.7.0-arm \
            goharbor/notary-server-photon:2.7.0-arm \
            goharbor/notary-signer-photon:2.7.0-arm \
            goharbor/harbor-registryctl:2.7.0-arm \
            goharbor/registry-photon:2.7.0-arm \
            goharbor/harbor-log:2.7.0-arm \
            goharbor/harbor-jobservice:2.7.0-arm \
            goharbor/harbor-core:2.7.0-arm \
            goharbor/harbor-portal:2.7.0-arm \
            goharbor/harbor-db:2.7.0-arm \
            goharbor/prepare:2.7.0-arm \
            goharbor/nginx-photon:2.7.0-arm \
            -o ~/harbor-2.7.0-images-arm.tar
          gzip ~/harbor-2.7.0-images-arm.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 2.7-release
          generate_release_notes: true
          files: ~/harbor-2.7.0-images-arm.tar.gz